# Generated by Django 5.2.9 on 2025-12-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Main_Content",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("B_I", models.IntegerField(blank=True, null=True)),
                ("B_H", models.CharField(blank=True, max_length=32, null=True)),
                ("B_A_S", models.CharField(blank=True, max_length=255, null=True)),
                ("B_L", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "表注释",
                "verbose_name_plural": "表注释",
                "db_table": "main_content",
            },
        ),
    ]
