# Generated by Django 5.2.9 on 2025-12-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mb2ou2iu", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="main_content",
            options={
                "managed": True,
                "verbose_name": "内容",
                "verbose_name_plural": "内容",
            },
        ),
        migrations.RemoveField(
            model_name="main_content",
            name="id",
        ),
        migrations.AlterField(
            model_name="main_content",
            name="B_A_S",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="地址"
            ),
        ),
        migrations.AlterField(
            model_name="main_content",
            name="B_H",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="标题"
            ),
        ),
        migrations.AlterField(
            model_name="main_content",
            name="B_I",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="字段号"
            ),
        ),
        migrations.AlterField(
            model_name="main_content",
            name="B_L",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="LOGO"
            ),
        ),
    ]
